/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#2C3947",
        "secondary": "#547A95",
        "tertiary": "#C2A56D",
        "page-background": "#E8EDF2",
        "card-background": "#F6F8FA",
        "on-surface": "#191c1e",
        "secondary-container": "#b8dffd",
        "primary-fixed-dim": "#bac8d9",
        "on-secondary-fixed-variant": "#224b64",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e1c388",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fb",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#d6e4f6",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "inverse-primary": "#bac8d9",
        "on-secondary-fixed": "#001e2e",
        "on-primary-container": "#95a2b3",
        "surface-container": "#eceef0",
        "outline": "#74777c",
        "secondary-fixed-dim": "#a5cbe9",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#261900",
        "outline-variant": "#c4c6cc",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#c8e6ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#ba9e66",
        "on-primary-fixed-variant": "#3b4856",
        "surface": "#f8f9fb",
        "on-tertiary-fixed-variant": "#594415",
        "on-primary-fixed": "#0f1d2a",
        "on-tertiary": "#ffffff",
        "primary-container": "#2c3947",
        "tertiary-container": "#483507",
        "on-secondary-container": "#3d637d",
        "on-surface-variant": "#44474c",
        "surface-tint": "#52606f",
        "background": "#E8EDF2",
        "tertiary-fixed": "#ffdea2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "sidebar-width": "280px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "display-lg-mobile": ["Fraunces", "serif"],
        "label-caps": ["IBM Plex Mono", "monospace"],
        "label-technical": ["IBM Plex Mono", "monospace"],
        "display-lg": ["Fraunces", "serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["Fraunces", "serif"],
        "display-md": ["Fraunces", "serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "38px", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "17px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-technical": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "29px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "29px", fontWeight: "500" }],
        "display-md": ["32px", { lineHeight: "35px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
